{{- if not .Values.agent.useExistingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "acapy.fullname" . }}
  labels:
    {{- include "acapy.labels" . | nindent 4 }}
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
    wallet-seed: {{  .Values.config.agentSeed | default (randAlphaNum 32) | b64enc | quote }}
    adminURLApiKey: {{ .Values.config.adminURLApiKey | default (randAlphaNum 32) | b64enc | quote }}
    wallet-key: {{ .Values.config.walletKey | default (randAlphaNum 32) | b64enc | quote }}
    {{- if .Values.config.jwtSecret }}
    jwtSecret: {{ .Values.config.jwtSecret | b64enc | quote }}
    {{- end }}
{{- end}}
---
{{- if not .Values.agent.db.useExistingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "acapy.fullname" . }}-db
  labels:
    {{- include "acapy.labels" . | nindent 4 }}
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  account: {{  .Values.config.postgres.account | default "acapy "| b64enc | quote }}
  password: {{  .Values.config.postgres.password | default (randAlphaNum 32) | b64enc | quote }}
  admin-account: {{  .Values.config.postgres.admin.account | default "postgres" | b64enc | quote }}
  admin-password: {{  .Values.config.postgres.admin.password | default (randAlphaNum 32) | b64enc | quote }}
{{- end}}
