{{- if not .Values.existingSecret -}}
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ include "indy-ledger-browser.fullname" . }}-wallet-credentials
  labels:
    {{- include "indy-ledger-browser.labels" . | nindent 4 }}
data:
  seed: {{ .Values.config.indy_wallet_seed | default (randAlphaNum 32) | b64enc | quote }}
{{- end -}}

